//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int BookId { get; set; }

        [Required]
        [Display(Name ="Book Name")]
        public string BookName { get; set; }

        [Required]
        [Display(Name = "Book Code")]
        public string BookCode { get; set; }


        [Required]
        [Display(Name = "Book Description")]
        public string Book_des { get; set; }
        
        [Display(Name = "Author Name")]
        [Required]
        public string Book_Auth { get; set; }

        [Required]
        [Display(Name = "Book Category")]
        public string Book_Cat { get; set; }

        [Required]
        [Display(Name = "Book Type")]
        public string Book_Type { get; set; }

        [Required]
        [Display(Name = "Book Option")]
        public string Book_Opt { get; set; }
        [Required]
        [Display(Name = "Discount")]
        public string Discount { get; set; }
        [Required]
        [Display(Name = "Rate")]
        public string Rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }


    }
}
