//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ResetPassword
    {
        public int ResetId { get; set; }
        [Display(Name ="What is Your Favourite Color?")]
        [Required]
        public string secretAns { get; set; }
        [Display(Name ="New Password")]
        [Required]
        public string NewPassword { get; set; }
        [Display(Name = "Confirm Password")]
        [Required]
        public string ConfirmPassword { get; set; }
    }
}
