//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBookProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public int StatusId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string status_Info { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual User User { get; set; }
    }
}
